### ISSUE TITLE
你这个APP有iOS版的吗？

### ISSUE THREAD

**Issue by zfl420** [hongui/FastAir#1]
打算开发iOS版本的吗？

**Comment by xiujiePei** [comment]
哈哈，我也想问呢！如果不复杂，打算做一个呢

**Comment by zevarc** [comment]
目前还没有，原理不复杂，只要支持DIrectWIFI就可以实现了

**Comment by zhubinsheng** [comment]
> 目前还没有，原理不复杂，只要支持DIrectWIFI就可以实现了

ios并不支持DIrectWIFI
